# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestSwiftyBootstrap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestSwiftyBootstrap
    # pod 'SwiftyBootstrap', :git => 'https://github.com/adeiji/SwiftyBootstrap.git', :tag => '1.38'
    pod 'SwiftyBootstrap', path: '../../SwiftyBootstrap'

end
