{"variants":[{"paths":["\/documentation\/swiftybootstrap"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftybootstrap"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/Column","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRCardSet","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRCurrentDevice","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRDevice","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/Margin"]},{"title":"Structures","identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/BootstrapMargin"]},{"title":"Enumerations","identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/ColSpan","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/DeviceSizes"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"SwiftyBootstrap","title":"SwiftyBootstrap","symbolKind":"module","role":"collection","modules":[{"name":"SwiftyBootstrap"}]},"hierarchy":{"paths":[[]]},"references":{"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement":{"role":"symbol","title":"GRBootstrapElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GRBootstrapElement"}],"abstract":[{"type":"text","text":"This class allows a user to layout an object similar to how Twitter Bootstrap works, with it’s elements spread across columns and rows."}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GRBootstrapElement"}],"url":"\/documentation\/swiftybootstrap\/grbootstrapelement"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/Column":{"role":"symbol","title":"Column","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Column"}],"abstract":[{"type":"text","text":"A column is used as a layout tool."}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/Column","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Column"}],"url":"\/documentation\/swiftybootstrap\/column"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/BootstrapMargin":{"role":"symbol","title":"BootstrapMargin","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BootstrapMargin"}],"abstract":[{"type":"text","text":"Margin that it used specifically within the GRBootstrapElement class."},{"type":"text","text":" "},{"type":"text","text":"This is the outer margin of the object."}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/BootstrapMargin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BootstrapMargin"}],"url":"\/documentation\/swiftybootstrap\/bootstrapmargin"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/Margin":{"role":"symbol","title":"Margin","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Margin"}],"abstract":[{"type":"text","text":"This class is responsible for handling the margins of a card set. *"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/Margin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Margin"}],"url":"\/documentation\/swiftybootstrap\/margin"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRDevice":{"role":"symbol","title":"GRDevice","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GRDevice"}],"abstract":[{"type":"text","text":"Checks to see which size the current device falls under"},{"type":"text","text":" "},{"type":"text","text":"For more information see documentation for GRCurrentDevice"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRDevice","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GRDevice"}],"url":"\/documentation\/swiftybootstrap\/grdevice"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/ColSpan":{"role":"symbol","title":"ColSpan","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ColSpan"}],"abstract":[{"type":"text","text":"The number of columns to span a UI element across. Similar to how a col span works with Bootstrap."}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/ColSpan","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ColSpan"}],"url":"\/documentation\/swiftybootstrap\/colspan"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/SwiftyBootstrapVersionNumber":{"role":"symbol","title":"SwiftyBootstrapVersionNumber","fragments":[{"kind":"identifier","text":"SwiftyBootstrapVersionNumber"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/SwiftyBootstrapVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/swiftybootstrapversionnumber"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRCardSet":{"role":"symbol","title":"GRCardSet","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GRCardSet"}],"abstract":[{"type":"text","text":"A card set is used by GRBootstrapElement to layout UI elements on the screen using rows and columns."}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRCardSet","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GRCardSet"}],"url":"\/documentation\/swiftybootstrap\/grcardset"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRCurrentDevice":{"role":"symbol","title":"GRCurrentDevice","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GRCurrentDevice"}],"abstract":[{"type":"text","text":"Contains classes responsible for detecting the size of the current device and helper methods to handle global state"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRCurrentDevice","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GRCurrentDevice"}],"url":"\/documentation\/swiftybootstrap\/grcurrentdevice"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/SwiftyBootstrapVersionString":{"role":"symbol","title":"SwiftyBootstrapVersionString","fragments":[{"kind":"identifier","text":"SwiftyBootstrapVersionString"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/SwiftyBootstrapVersionString","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/swiftybootstrapversionstring"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/DeviceSizes":{"role":"symbol","title":"DeviceSizes","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceSizes"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/DeviceSizes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeviceSizes"}],"url":"\/documentation\/swiftybootstrap\/devicesizes"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRMessageCard":{"role":"symbol","title":"GRMessageCard","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GRMessageCard"}],"abstract":[{"type":"text","text":"This is a simple helper class that extends GRBootstrapElement.  It contains nothing more than a message and a button that says “Okay” by default"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GRMessageCard"}],"url":"\/documentation\/swiftybootstrap\/grmessagecard"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap":{"role":"collection","title":"SwiftyBootstrap","abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/Column","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRCurrentDevice","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard"]},{"title":"Variables","identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/SwiftyBootstrapVersionNumber","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/SwiftyBootstrapVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRBootstrapElement\/title","value":"GRBootstrapElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRBootstrapElement\/fragments","value":[{"kind":"identifier","text":"GRBootstrapElement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1Column\/title","value":"Column"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1Column\/fragments","value":[{"kind":"identifier","text":"Column"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRCurrentDevice\/title","value":"GRCurrentDevice"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRCurrentDevice\/fragments","value":[{"kind":"identifier","text":"GRCurrentDevice"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRMessageCard\/title","value":"GRMessageCard"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRMessageCard\/fragments","value":[{"kind":"identifier","text":"GRMessageCard"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}