{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GRBootstrapElement"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Each bootstrap element must contain at least one row.  You can then add UI elements inside of columns to create a responsive UI."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Below is an example:"}]},{"type":"codeListing","syntax":null,"code":["card.addRow(columns: [","    Column(UILabel().withAttributes(closure: { view in","        let label = view as? UILabel","        label?.text = \"This is just an example.\"","    })","    .cardSet(),","        \/* When the screen is very","         small like an iPhone in","         portrait or on the side of the screen in","         split screen mode then","         span the full width of","         the screen *\/","        xsColSpan: .Twelve)","        \/** When the screen is","         smaller like an iPhone","         in landscape mode or half","         of the screen in split","         screen mode then span","         half the width of the","         screen *\/","        .forSize(.sm, .Six)","        \/** When the screen is","         medium size like an","         iPad in portrait mode","         then the width of this","         label will be 1\/4 the","         width of the screen *\/","        .forSize(.md, .Three)","], anchorToBottom: true)","","card.addToSuperview(superview: self.view)"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/swiftybootstrap\/grbootstrapelement"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftybootstrap\/grbootstrapelement"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)NSCoding","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)NSObject","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.SwiftyBootstrap\/7SnapKit25ConstraintRelatableTargetP","doc:\/\/org.cocoapods.SwiftyBootstrap\/7SnapKit20LayoutConstraintItemP","doc:\/\/org.cocoapods.SwiftyBootstrap\/s7CVarArgP","doc:\/\/org.cocoapods.SwiftyBootstrap\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SwiftyBootstrap\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SwiftyBootstrap\/SQ","doc:\/\/org.cocoapods.SwiftyBootstrap\/SH","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This class allows a user to layout an object similar to how Twitter Bootstrap works, with it’s elements spread across columns and rows."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GRBootstrapElement"}],"title":"GRBootstrapElement","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SwiftyBootstrap@objc(cs)GRBootstrapElement","modules":[{"name":"SwiftyBootstrap"}],"navigatorTitle":[{"kind":"identifier","text":"GRBootstrapElement"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap"]]},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/Column","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/Row"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/init(coder:)","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/init(color:anchorWidthToSuperviewWidth:margin:superview:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/anchorLastElementToBottom","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/anchorToBottom","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/anchorWidthToSuperviewWidth","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/bottomConstraint","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/horizontalLayout","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/margin","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/rows","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/topConstraint","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/viewAbove"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/addElement(element:atIndex:)","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/addRow(columns:widthInPixels:anchorToBottom:)","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/addToSuperview(superview:viewAbove:anchorToBottom:)","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/getElementNamed(_:superCardElements:)","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/hitTest(_:with:)","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/layoutSubviews()","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/removeElementNamed(_:)","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/removeElements()","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/slideDown(superview:margin:width:forTimeInterval:)","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/slideDownAndRemove(superview:)","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/slideUp(superview:margin:width:timeInterval:)","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/slideUpAndRemove(superview:)"]}],"references":{"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/anchorLastElementToBottom":{"role":"symbol","title":"anchorLastElementToBottom","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorLastElementToBottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether or not to anchor the last element in the elements array to the bottom of the card."}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/anchorLastElementToBottom","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/anchorlastelementtobottom"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/horizontalLayout":{"role":"symbol","title":"horizontalLayout","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"horizontalLayout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether or line up the contents of this card horizontally"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/horizontalLayout","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/horizontallayout"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/bottomConstraint":{"role":"symbol","title":"bottomConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Constraint","preciseIdentifier":"s:7SnapKit10ConstraintC"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"This is the constraint that attaches the last element to the bottom of the Card. It’s an open parameter because you can set this constraint yourself if you manually set bottom constraint and don’t use the anchorToBottom parameter of the addRow method"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/bottomConstraint","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/bottomconstraint"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIAppearance"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/removeElements()":{"role":"symbol","title":"removeElements()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeElements"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Remove all the UI elements of this Bootstrap Element from the screen and remove the reference to those UI elements from this class"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/removeElements()","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/removeelements()"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.SwiftyBootstrap/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(cs)UIView"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.SwiftyBootstrap/7SnapKit25ConstraintRelatableTargetP":{"type":"unresolvable","title":"SnapKit.ConstraintRelatableTarget","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/7SnapKit25ConstraintRelatableTargetP"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement":{"role":"symbol","title":"GRBootstrapElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GRBootstrapElement"}],"abstract":[{"type":"text","text":"This class allows a user to layout an object similar to how Twitter Bootstrap works, with it’s elements spread across columns and rows."}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GRBootstrapElement"}],"url":"\/documentation\/swiftybootstrap\/grbootstrapelement"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/viewAbove":{"role":"symbol","title":"viewAbove","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewAbove"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/viewAbove","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/viewabove"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/removeElementNamed(_:)":{"role":"symbol","title":"removeElementNamed(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeElementNamed"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Remove an element of a given name"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/removeElementNamed(_:)","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/removeelementnamed(_:)"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/slideDown(superview:margin:width:forTimeInterval:)":{"role":"symbol","title":"slideDown(superview:margin:width:forTimeInterval:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"slideDown"},{"kind":"text","text":"("},{"kind":"externalParam","text":"superview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"margin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forTimeInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Slides the card down and then adds it to the superview. This method is more so used when you trying to display something like a card. For example, if you want to display a quick message to the user, then you would most likely use this method. See GRMessageCard"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/slideDown(superview:margin:width:forTimeInterval:)","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/slidedown(superview:margin:width:fortimeinterval:)"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/Column":{"role":"symbol","title":"GRBootstrapElement.Column","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Column"}],"abstract":[{"type":"text","text":"A column is used as a layout tool."}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/Column","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Column"}],"url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/column"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)NSObject"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/addRow(columns:widthInPixels:anchorToBottom:)":{"role":"symbol","title":"addRow(columns:widthInPixels:anchorToBottom:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addRow"},{"kind":"text","text":"("},{"kind":"externalParam","text":"columns"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Column","preciseIdentifier":"s:15SwiftyBootstrap18GRBootstrapElementC6ColumnC"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"widthInPixels"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"anchorToBottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"GRBootstrapElement","preciseIdentifier":"c:@M@SwiftyBootstrap@objc(cs)GRBootstrapElement"}],"abstract":[{"type":"text","text":"Add a row to the element. Rows are similar to Bootstrap rows. They obviously always start on a new line and they consist of columns with various attributes which define how they display on the"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/addRow(columns:widthInPixels:anchorToBottom:)","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/addrow(columns:widthinpixels:anchortobottom:)"},"doc://org.cocoapods.SwiftyBootstrap/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/SQ"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.SwiftyBootstrap/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/s23CustomStringConvertibleP"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/init(color:anchorWidthToSuperviewWidth:margin:superview:)":{"role":"symbol","title":"init(color:anchorWidthToSuperviewWidth:margin:superview:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"anchorWidthToSuperviewWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"margin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BootstrapMargin","preciseIdentifier":"s:15SwiftyBootstrap0B6MarginV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"superview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Initialize a new GRBootstrapElement object"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/init(color:anchorWidthToSuperviewWidth:margin:superview:)","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/init(color:anchorwidthtosuperviewwidth:margin:superview:)"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/Row":{"role":"symbol","title":"GRBootstrapElement.Row","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Row"}],"abstract":[{"type":"text","text":"A row is similar to a row in Twitter Bootstrap."}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/Row","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Row"}],"url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/row"},"doc://org.cocoapods.SwiftyBootstrap/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/margin":{"role":"symbol","title":"margin","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"margin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BootstrapMargin","preciseIdentifier":"s:15SwiftyBootstrap0B6MarginV"}],"abstract":[{"type":"text","text":"The margin of the card when it’s added to the superview"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/margin","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/margin"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/rows":{"role":"symbol","title":"rows","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rows"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Row","preciseIdentifier":"s:15SwiftyBootstrap18GRBootstrapElementC3RowC"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/rows","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/rows"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/slideUp(superview:margin:width:timeInterval:)":{"role":"symbol","title":"slideUp(superview:margin:width:timeInterval:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"slideUp"},{"kind":"text","text":"("},{"kind":"externalParam","text":"superview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"margin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"timeInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"See slideDown method of this class"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/slideUp(superview:margin:width:timeInterval:)","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/slideup(superview:margin:width:timeinterval:)"},"doc://org.cocoapods.SwiftyBootstrap/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/s7CVarArgP"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/hitTest(_:with:)":{"role":"symbol","title":"hitTest(_:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hitTest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The reason why we’re overriding this function is because we need to make sure that we only get the view that we want when the user touches the screen."}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/hitTest(_:with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hitTest:withEvent:"}],"url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/hittest(_:with:)"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIFocusItem"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap":{"role":"collection","title":"SwiftyBootstrap","abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRMessageCard":{"role":"symbol","title":"GRMessageCard","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GRMessageCard"}],"abstract":[{"type":"text","text":"This is a simple helper class that extends GRBootstrapElement.  It contains nothing more than a message and a button that says “Okay” by default"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GRMessageCard"}],"url":"\/documentation\/swiftybootstrap\/grmessagecard"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/anchorToBottom":{"role":"symbol","title":"anchorToBottom","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorToBottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Whether or not this card should be anchored to the bottom of it’s superview"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/anchorToBottom","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/anchortobottom"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/layoutSubviews()":{"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/layoutsubviews()"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/addElement(element:atIndex:)":{"role":"symbol","title":"addElement(element:atIndex:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addElement"},{"kind":"text","text":"("},{"kind":"externalParam","text":"element"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GRCardSet","preciseIdentifier":"s:15SwiftyBootstrap9GRCardSetC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"atIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Add an element to the card."},{"type":"text","text":" "},{"type":"text","text":"This function adds the card to the end of the elements array "},{"type":"emphasis","inlineContent":[{"type":"text","text":"IF"}]},{"type":"text","text":" you don’t input anything for the atIndex parameter."},{"type":"text","text":" "},{"type":"text","text":"If this card has already been added to a view than you will need to call the redraw() method"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/addElement(element:atIndex:)","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/addelement(element:atindex:)"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/init(coder:)"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/topConstraint":{"role":"symbol","title":"topConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Constraint","preciseIdentifier":"s:7SnapKit10ConstraintC"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The top constraint of the card."}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/topConstraint","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/topconstraint"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/anchorWidthToSuperviewWidth":{"role":"symbol","title":"anchorWidthToSuperviewWidth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorWidthToSuperviewWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to set the maximum width of this card to the width of the superview.  If this is set to "},{"type":"strong","inlineContent":[{"type":"text","text":"true"}]},{"type":"text","text":" then cards that will go beyond the width of the superview will automatically be pushed to the next line."}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/anchorWidthToSuperviewWidth","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/anchorwidthtosuperviewwidth"},"doc://org.cocoapods.SwiftyBootstrap/7SnapKit20LayoutConstraintItemP":{"type":"unresolvable","title":"SnapKit.LayoutConstraintItem","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/7SnapKit20LayoutConstraintItemP"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)NSCoding"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/addToSuperview(superview:viewAbove:anchorToBottom:)":{"role":"symbol","title":"addToSuperview(superview:viewAbove:anchorToBottom:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addToSuperview"},{"kind":"text","text":"("},{"kind":"externalParam","text":"superview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewAbove"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"anchorToBottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Add the card to a view"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/addToSuperview(superview:viewAbove:anchorToBottom:)","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/addtosuperview(superview:viewabove:anchortobottom:)"},"doc://org.cocoapods.SwiftyBootstrap/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/SH"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/slideUpAndRemove(superview:)":{"role":"symbol","title":"slideUpAndRemove(superview:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"slideUpAndRemove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"superview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Slide this element up and then remove it from it’s superview"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/slideUpAndRemove(superview:)","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/slideupandremove(superview:)"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/slideDownAndRemove(superview:)":{"role":"symbol","title":"slideDownAndRemove(superview:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"slideDownAndRemove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"superview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Slide this element down and then remove it from it’s superview"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/slideDownAndRemove(superview:)","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/slidedownandremove(superview:)"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/getElementNamed(_:superCardElements:)":{"role":"symbol","title":"getElementNamed(_:superCardElements:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getElementNamed"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"superCardElements"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GRCardSet","preciseIdentifier":"s:15SwiftyBootstrap9GRCardSetC"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"GRCardSet","preciseIdentifier":"s:15SwiftyBootstrap9GRCardSetC"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get a child cardset of this bootstrap element section"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/getElementNamed(_:superCardElements:)","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/getelementnamed(_:supercardelements:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GRBootstrapElement"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GRBootstrapElement"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GRBootstrapElement"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/hitTest(_:with:)","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/init(coder:)","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/layoutSubviews()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GRBootstrapElement"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRBootstrapElement\/title","value":"GRBootstrapElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRBootstrapElement\/fragments","value":[{"kind":"identifier","text":"GRBootstrapElement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRBootstrapElement~1hitTest(_:with:)\/title","value":"hitTest:withEvent:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRBootstrapElement~1hitTest(_:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hitTest:withEvent:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRMessageCard\/title","value":"GRMessageCard"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRMessageCard\/fragments","value":[{"kind":"identifier","text":"GRMessageCard"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRBootstrapElement~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRBootstrapElement~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRBootstrapElement~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRBootstrapElement~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}