{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GRCurrentDevice"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/swiftybootstrap\/grcurrentdevice"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftybootstrap\/grcurrentdevice"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)NSCoding","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)NSObject","doc:\/\/org.cocoapods.SwiftyBootstrap\/s7CVarArgP","doc:\/\/org.cocoapods.SwiftyBootstrap\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SwiftyBootstrap\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SwiftyBootstrap\/SQ","doc:\/\/org.cocoapods.SwiftyBootstrap\/SH","doc:\/\/org.cocoapods.SwiftyBootstrap\/s8SendableP","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRCurrentDevice","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Contains classes responsible for detecting the size of the current device and helper methods to handle global state"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GRCurrentDevice"}],"title":"GRCurrentDevice","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SwiftyBootstrap@objc(cs)GRCurrentDevice","modules":[{"name":"SwiftyBootstrap"}],"navigatorTitle":[{"kind":"identifier","text":"GRCurrentDevice"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRCurrentDevice\/size"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRCurrentDevice\/getTopController()"]},{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRCurrentDevice\/shared"]},{"title":"Type Methods","identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRCurrentDevice\/getCorrectWidth()","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRCurrentDevice\/getScreenSize()"]}],"references":{"doc://org.cocoapods.SwiftyBootstrap/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)NSExtensionRequestHandling"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap":{"role":"collection","title":"SwiftyBootstrap","abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRCurrentDevice/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GRCurrentDevice","preciseIdentifier":"c:@M@SwiftyBootstrap@objc(cs)GRCurrentDevice"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRCurrentDevice\/shared","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grcurrentdevice\/shared"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRCurrentDevice/getScreenSize()":{"role":"symbol","title":"getScreenSize()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getScreenSize"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"DeviceSizes","preciseIdentifier":"s:15SwiftyBootstrap11DeviceSizesO"}],"abstract":[{"type":"text","text":"Get what the current screen size is, ex large, small, very large etc.  Currently on returns small or large"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRCurrentDevice\/getScreenSize()","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grcurrentdevice\/getscreensize()"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIContentContainer"},"doc://org.cocoapods.SwiftyBootstrap/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/s8SendableP"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRCurrentDevice/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRCurrentDevice\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/swiftybootstrap\/grcurrentdevice\/initwithcoder:"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRCurrentDevice/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRCurrentDevice\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/swiftybootstrap\/grcurrentdevice\/initwithnibname:bundle:"},"doc://org.cocoapods.SwiftyBootstrap/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/SQ"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIStateRestoring"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRCurrentDevice/getCorrectWidth()":{"role":"symbol","title":"getCorrectWidth()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCorrectWidth"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"If in landscape mode we need the width to be whatever the highest dimension is since unfortunately sometimes the height and"},{"type":"text","text":" "},{"type":"text","text":"the width values are switched.  So for example, in landscape if the height is reading as 1134 and the width 865, we know that we"},{"type":"text","text":" "},{"type":"text","text":"need to use the height value since in landscape width is always greater than height"},{"type":"text","text":" "},{"type":"text","text":"This works vice versa for portrait"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRCurrentDevice\/getCorrectWidth()","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grcurrentdevice\/getcorrectwidth()"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.SwiftyBootstrap/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)NSObject"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRCurrentDevice/size":{"role":"symbol","title":"size","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DeviceSizes","preciseIdentifier":"s:15SwiftyBootstrap11DeviceSizesO"}],"abstract":[{"type":"text","text":"This will change with every change of layout within the app.  My meaning is, that if the user goes from say portrait to landscape, then if on a phone, that change will be going from .xs to .sm and that change will be reflected here."}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRCurrentDevice\/size","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grcurrentdevice\/size"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRCurrentDevice":{"role":"symbol","title":"GRCurrentDevice","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GRCurrentDevice"}],"abstract":[{"type":"text","text":"Contains classes responsible for detecting the size of the current device and helper methods to handle global state"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRCurrentDevice","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GRCurrentDevice"}],"url":"\/documentation\/swiftybootstrap\/grcurrentdevice"},"doc://org.cocoapods.SwiftyBootstrap/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(cs)UIViewController"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)NSCoding"},"doc://org.cocoapods.SwiftyBootstrap/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/s7CVarArgP"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.SwiftyBootstrap/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/SH"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRCurrentDevice/getTopController()":{"role":"symbol","title":"getTopController()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTopController"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A convenience method to get the current top most view controller"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRCurrentDevice\/getTopController()","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grcurrentdevice\/gettopcontroller()"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.SwiftyBootstrap/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GRCurrentDevice"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GRCurrentDevice"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GRCurrentDevice"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRCurrentDevice\/initWithCoder:","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRCurrentDevice\/initWithNibName:bundle:"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GRCurrentDevice"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRCurrentDevice\/title","value":"GRCurrentDevice"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRCurrentDevice\/fragments","value":[{"kind":"identifier","text":"GRCurrentDevice"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}