{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GRMessageCard"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"By default, when the okayButton is pressed it will simply close the card, however, you can override this functionality simply by changing the target of the okayButton property."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"There is also much more that you can do, for example you can…"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Add a second button."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Add a text field"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"And then since it’s an instance of GRBootstrapSection you can add rows like any other BootstrapElement. However, if you’re going to be doing a lot of customization then you may as well just use GRBootstrapElement directly"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/swiftybootstrap\/grmessagecard"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftybootstrap\/grmessagecard"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)NSCoding","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)NSObject","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.SwiftyBootstrap\/7SnapKit25ConstraintRelatableTargetP","doc:\/\/org.cocoapods.SwiftyBootstrap\/7SnapKit20LayoutConstraintItemP","doc:\/\/org.cocoapods.SwiftyBootstrap\/s7CVarArgP","doc:\/\/org.cocoapods.SwiftyBootstrap\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SwiftyBootstrap\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SwiftyBootstrap\/SQ","doc:\/\/org.cocoapods.SwiftyBootstrap\/SH","doc:\/\/org.cocoapods.SwiftyBootstrap\/s8SendableP","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is a simple helper class that extends GRBootstrapElement.  It contains nothing more than a message and a button that says “Okay” by default"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GRMessageCard"}],"title":"GRMessageCard","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SwiftyBootstrap@objc(cs)GRMessageCard","modules":[{"name":"SwiftyBootstrap"}],"navigatorTitle":[{"kind":"identifier","text":"GRMessageCard"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard\/init(coder:)","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard\/init(color:anchorWidthToSuperviewWidth:margin:superview:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard\/firstButton","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard\/messageLabel","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard\/secondButton","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard\/textField"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard\/close()","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard\/draw(message:title:buttonBackgroundColor:superview:buttonText:cancelButtonText:isError:)"]}],"references":{"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRMessageCard/firstButton":{"role":"symbol","title":"firstButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"This is the top button. It by default is the okay button."}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard\/firstButton","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grmessagecard\/firstbutton"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)NSObject"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRMessageCard/secondButton":{"role":"symbol","title":"secondButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"This is the bottom button."}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard\/secondButton","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grmessagecard\/secondbutton"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement":{"role":"symbol","title":"GRBootstrapElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GRBootstrapElement"}],"abstract":[{"type":"text","text":"This class allows a user to layout an object similar to how Twitter Bootstrap works, with it’s elements spread across columns and rows."}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GRBootstrapElement"}],"url":"\/documentation\/swiftybootstrap\/grbootstrapelement"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.SwiftyBootstrap/7SnapKit20LayoutConstraintItemP":{"type":"unresolvable","title":"SnapKit.LayoutConstraintItem","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/7SnapKit20LayoutConstraintItemP"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRMessageCard/close()":{"role":"symbol","title":"close()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"close"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Slide the message card out of view and removes it from the superview."}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard\/close()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"close"}],"url":"\/documentation\/swiftybootstrap\/grmessagecard\/close()"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.SwiftyBootstrap/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/s23CustomStringConvertibleP"},"doc://org.cocoapods.SwiftyBootstrap/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/s8SendableP"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIFocusItem"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRMessageCard":{"role":"symbol","title":"GRMessageCard","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GRMessageCard"}],"abstract":[{"type":"text","text":"This is a simple helper class that extends GRBootstrapElement.  It contains nothing more than a message and a button that says “Okay” by default"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GRMessageCard"}],"url":"\/documentation\/swiftybootstrap\/grmessagecard"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRMessageCard/init(color:anchorWidthToSuperviewWidth:margin:superview:)":{"role":"symbol","title":"init(color:anchorWidthToSuperviewWidth:margin:superview:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"anchorWidthToSuperviewWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"margin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BootstrapMargin","preciseIdentifier":"s:15SwiftyBootstrap0B6MarginV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"superview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Create a new instance of the GRMessageCard class"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard\/init(color:anchorWidthToSuperviewWidth:margin:superview:)","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grmessagecard\/init(color:anchorwidthtosuperviewwidth:margin:superview:)"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.SwiftyBootstrap/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/s7CVarArgP"},"doc://org.cocoapods.SwiftyBootstrap/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.SwiftyBootstrap/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/SQ"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap":{"role":"collection","title":"SwiftyBootstrap","abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap"},"doc://org.cocoapods.SwiftyBootstrap/7SnapKit25ConstraintRelatableTargetP":{"type":"unresolvable","title":"SnapKit.ConstraintRelatableTarget","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/7SnapKit25ConstraintRelatableTargetP"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRMessageCard/messageLabel":{"role":"symbol","title":"messageLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The label that displays the main information on the message card"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard\/messageLabel","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grmessagecard\/messagelabel"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRMessageCard/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/swiftybootstrap\/grmessagecard\/init(coder:)"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.SwiftyBootstrap/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/SH"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRMessageCard/draw(message:title:buttonBackgroundColor:superview:buttonText:cancelButtonText:isError:)":{"role":"symbol","title":"draw(message:title:buttonBackgroundColor:superview:buttonText:cancelButtonText:isError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"draw"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"buttonBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"superview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"buttonText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cancelButtonText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Displays the message card on the screen with the given parameters.  It also blurs the view that is responsible for showing it"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard\/draw(message:title:buttonBackgroundColor:superview:buttonText:cancelButtonText:isError:)","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grmessagecard\/draw(message:title:buttonbackgroundcolor:superview:buttontext:cancelbuttontext:iserror:)"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)NSCoding"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRMessageCard/textField":{"role":"symbol","title":"textField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The text field that is added to the message card, if there is one added. See addTextField:Bool"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard\/textField","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap\/grmessagecard\/textfield"},"doc://org.cocoapods.SwiftyBootstrap/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/objc(pl)UIAppearance"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GRMessageCard"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GRMessageCard"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GRMessageCard"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard\/close()","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard\/init(coder:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GRMessageCard"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement","preciseIdentifier":"c:@M@SwiftyBootstrap@objc(cs)GRBootstrapElement","text":"GRBootstrapElement"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRBootstrapElement\/title","value":"GRBootstrapElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRBootstrapElement\/fragments","value":[{"kind":"identifier","text":"GRBootstrapElement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRMessageCard~1close()\/title","value":"close"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRMessageCard~1close()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"close"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRMessageCard\/title","value":"GRMessageCard"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRMessageCard\/fragments","value":[{"kind":"identifier","text":"GRMessageCard"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRMessageCard~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRMessageCard~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}