{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"close"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"It is recommended that you use this function to remove this card from the superview. You can remove it manually, however, there are certain clean up tasks that are executed within this method also."}]}],"type":"aside","name":"Important"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/swiftybootstrap\/grmessagecard\/close()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftybootstrap\/grmessagecard\/close()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard\/close()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Slide the message card out of view and removes it from the superview."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"close"},{"kind":"text","text":"()"}],"title":"close()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SwiftyBootstrap@objc(cs)GRMessageCard(im)close","modules":[{"name":"SwiftyBootstrap"}],"navigatorTitle":[{"kind":"identifier","text":"close"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard"]]},"references":{"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRMessageCard/close()":{"role":"symbol","title":"close()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"close"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Slide the message card out of view and removes it from the superview."}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard\/close()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"close"}],"url":"\/documentation\/swiftybootstrap\/grmessagecard\/close()"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap":{"role":"collection","title":"SwiftyBootstrap","abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRMessageCard":{"role":"symbol","title":"GRMessageCard","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GRMessageCard"}],"abstract":[{"type":"text","text":"This is a simple helper class that extends GRBootstrapElement.  It contains nothing more than a message and a button that says “Okay” by default"}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRMessageCard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GRMessageCard"}],"url":"\/documentation\/swiftybootstrap\/grmessagecard"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"close"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"close"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"close"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRMessageCard~1close()\/title","value":"close"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRMessageCard~1close()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"close"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRMessageCard\/title","value":"GRMessageCard"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRMessageCard\/fragments","value":[{"kind":"identifier","text":"GRMessageCard"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}