{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aDecoder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/swiftybootstrap\/grbootstrapelement\/init(coder:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftybootstrap\/grbootstrapelement\/init(coder:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/init(coder:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"title":"init(coder:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@SwiftyBootstrap@objc(cs)GRBootstrapElement(im)initWithCoder:","modules":[{"name":"SwiftyBootstrap"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap","doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement"]]},"references":{"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/swiftybootstrap\/grbootstrapelement\/init(coder:)"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap/GRBootstrapElement":{"role":"symbol","title":"GRBootstrapElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GRBootstrapElement"}],"abstract":[{"type":"text","text":"This class allows a user to layout an object similar to how Twitter Bootstrap works, with it’s elements spread across columns and rows."}],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap\/GRBootstrapElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GRBootstrapElement"}],"url":"\/documentation\/swiftybootstrap\/grbootstrapelement"},"doc://org.cocoapods.SwiftyBootstrap/documentation/SwiftyBootstrap":{"role":"collection","title":"SwiftyBootstrap","abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyBootstrap\/documentation\/SwiftyBootstrap","kind":"symbol","type":"topic","url":"\/documentation\/swiftybootstrap"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithCoder:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCoder:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aDecoder"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRBootstrapElement~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRBootstrapElement~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRBootstrapElement\/title","value":"GRBootstrapElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SwiftyBootstrap~1documentation~1SwiftyBootstrap~1GRBootstrapElement\/fragments","value":[{"kind":"identifier","text":"GRBootstrapElement"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}