# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftyBootstrap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftyBootstrap
  pod 'SnapKit'

  target 'SwiftyBootstrapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftyBootstrapUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
